#############################################################################
# Generated by PAGE version 4.19
#  in conjunction with Tcl version 8.6
#  Jan 01, 2019 05:15:28 PM EET  platform: Linux
set vTcl(timestamp) ""


if {!$vTcl(borrow)} {

vTcl:font:add_GUI_font TkDefaultFont \
"-family sans-serif -size 10 -weight normal -slant roman -underline 0 -overstrike 0"
vTcl:font:add_GUI_font TkFixedFont \
"-family monospace -size 10 -weight normal -slant roman -underline 0 -overstrike 0"
vTcl:font:add_GUI_font TkMenuFont \
"-family sans-serif -size 10 -weight normal -slant roman -underline 0 -overstrike 0"
vTcl:font:add_GUI_font TkTextFont \
"-family sans-serif -size 10 -weight normal -slant roman -underline 0 -overstrike 0"
set vTcl(actual_gui_font_dft_name) TkDefaultFont
set vTcl(actual_gui_font_menu_name) TkMenuFont
set vTcl(actual_gui_bg) #d9d9d9
set vTcl(actual_gui_fg) #000000
set vTcl(actual_gui_analog) #ececec
set vTcl(actual_gui_menu_analog) #ececec
set vTcl(actual_gui_menu_bg) #d9d9d9
set vTcl(actual_gui_menu_fg) #000000
set vTcl(complement_color) #d9d9d9
set vTcl(analog_color_p) #d9d9d9
set vTcl(analog_color_m) #ececec
set vTcl(active_fg) #000000
set vTcl(actual_gui_menu_active_bg)  #ececec
set vTcl(active_menu_fg) #000000
}

#################################
#LIBRARY PROCEDURES
#


if {[info exists vTcl(sourcing)]} {

proc vTcl:project:info {} {
    set base .top42
    global vTcl
    set base $vTcl(btop)
    if {$base == ""} {
        set base .top42
    }
    namespace eval ::widgets::$base {
        set dflt,origin 0
        set runvisible 1
    }
    namespace eval ::widgets_bindings {
        set tagslist {_TopLevel _vTclBalloon}
    }
    namespace eval ::vTcl::modules::main {
        set procs {
        }
        set compounds {
        }
        set projectType single
    }
}
}

#################################
# GENERATED GUI PROCEDURES
#

proc vTclWindow.top42 {base} {
    if {$base == ""} {
        set base .top42
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    ###################
    # CREATING WIDGETS
    ###################
    vTcl::widgets::core::toplevel::createCmd $top -class Toplevel \
        -menu "$top.m44" -background {#707070} -highlightcolor black 
    wm focusmodel $top passive
    wm geometry $top 1299x681+67+27
    update
    # set in toplevel.wgt.
    global vTcl
    global img_list
    set vTcl(save,dflt,origin) 0
    wm maxsize $top 1351 738
    wm minsize $top 1 1
    wm overrideredirect $top 0
    wm resizable $top 1 1
    wm deiconify $top
    wm title $top "New Toplevel"
    vTcl:DefineAlias "$top" "Toplevel1" vTcl:Toplevel:WidgetProc "" 1
    canvas $top.can43 \
        -background {#d9d9d9} -borderwidth 2 -closeenough 1.0 -height 561 \
        -highlightcolor black -insertbackground black -relief ridge \
        -selectbackground {#c4c4c4} -selectforeground black -width 981 
    vTcl:DefineAlias "$top.can43" "Canvas1" vTcl:WidgetProc "Toplevel1" 1
    button $top.but60 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -font TkDefaultFont -foreground {#000000} \
        -highlightcolor black -text Reconnect 
    vTcl:DefineAlias "$top.but60" "Button3" vTcl:WidgetProc "Toplevel1" 1
    labelframe $top.lab65 \
        -font TkDefaultFont -foreground black -text {Save as} \
        -background {#d9d9d9} -height 55 -highlightcolor black -width 490 
    vTcl:DefineAlias "$top.lab65" "Labelframe2" vTcl:WidgetProc "Toplevel1" 1
    set site_3_0 $top.lab65
    message $site_3_0.mes66 \
        -background {#d9d9d9} -font TkDefaultFont -foreground {#000000} \
        -highlightcolor black -text Message -width 222 
    vTcl:DefineAlias "$site_3_0.mes66" "Message1" vTcl:WidgetProc "Toplevel1" 1
    button $site_3_0.but67 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -font TkDefaultFont -foreground {#000000} \
        -highlightcolor black -text Browse 
    vTcl:DefineAlias "$site_3_0.but67" "Button2" vTcl:WidgetProc "Toplevel1" 1
    entry $site_3_0.ent69 \
        -background white -font TkFixedFont -foreground {#000000} \
        -highlightcolor black -insertbackground black \
        -selectbackground {#c4c4c4} -selectforeground black 
    vTcl:DefineAlias "$site_3_0.ent69" "Entry2" vTcl:WidgetProc "Toplevel1" 1
    place $site_3_0.mes66 \
        -in $site_3_0 -x 104 -y 18 -width 222 -relwidth 0 -height 25 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.but67 \
        -in $site_3_0 -x 9 -y 18 -width 71 -height 31 -anchor nw \
        -bordermode ignore 
    place $site_3_0.ent69 \
        -in $site_3_0 -x 334 -y 20 -width 146 -relwidth 0 -height 23 \
        -relheight 0 -anchor nw -bordermode ignore 
    labelframe $top.lab93 \
        -font TkDefaultFont -foreground black -text {Transmit Signal} \
        -background {#d9d9d9} -height 55 -highlightcolor black -width 480 
    vTcl:DefineAlias "$top.lab93" "Labelframe2_11" vTcl:WidgetProc "Toplevel1" 1
    set site_3_0 $top.lab93
    message $site_3_0.mes66 \
        -background {#d9d9d9} -font TkDefaultFont -foreground {#000000} \
        -highlightcolor black -text Message -width 222 
    vTcl:DefineAlias "$site_3_0.mes66" "Message1_12" vTcl:WidgetProc "Toplevel1" 1
    button $site_3_0.but67 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -font TkDefaultFont -foreground {#000000} \
        -highlightcolor black -text Browse 
    vTcl:DefineAlias "$site_3_0.but67" "Button2_13" vTcl:WidgetProc "Toplevel1" 1
    entry $site_3_0.ent69 \
        -background white -font TkFixedFont -foreground {#000000} \
        -highlightcolor black -insertbackground black \
        -selectbackground {#c4c4c4} -selectforeground black 
    vTcl:DefineAlias "$site_3_0.ent69" "Entry2_14" vTcl:WidgetProc "Toplevel1" 1
    place $site_3_0.mes66 \
        -in $site_3_0 -x 96 -y 18 -width 222 -relwidth 0 -height 25 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.but67 \
        -in $site_3_0 -x 9 -y 18 -width 71 -height 31 -anchor nw \
        -bordermode ignore 
    place $site_3_0.ent69 \
        -in $site_3_0 -x 327 -y 20 -width 146 -relwidth 0 -height 23 \
        -relheight 0 -anchor nw -bordermode ignore 
    ttk::progressbar $top.tPr43
    vTcl:DefineAlias "$top.tPr43" "TProgressbar1" vTcl:WidgetProc "Toplevel1" 1
    set site_3_0 $top.m44
    menu $site_3_0 \
        -activebackground {#ececec} -activeforeground {#000000} \
        -background {#d9d9d9} -font TkMenuFont -foreground {#000000} \
        -tearoff 0 
    $site_3_0 add command \
        -activebackground {#ececec} -activeforeground {#000000} \
        -background {#d9d9d9} -command {#StartSigGen} \
        -font [vTcl:font:getFontFromDescr "-family sans-serif -size 10 -weight normal -slant roman -underline 0 -overstrike 0"] \
        -foreground {#000000} -label {Signal Generator} 
    ttk::style configure TNotebook -background #d9d9d9
    ttk::style configure TNotebook.Tab -background #d9d9d9
    ttk::style configure TNotebook.Tab -foreground #000000
    ttk::style configure TNotebook.Tab -font TkDefaultFont
    ttk::style map TNotebook.Tab -background [list disabled #d9d9d9 selected #d9d9d9]
    ttk::notebook $top.tNo55 \
        -width 292 -height 616 -takefocus {} 
    vTcl:DefineAlias "$top.tNo55" "TNotebook1" vTcl:WidgetProc "Toplevel1" 1
    frame $top.tNo55.t0 \
        -background {#d9d9d9} -highlightcolor black 
    vTcl:DefineAlias "$top.tNo55.t0" "TNotebook1_t1" vTcl:WidgetProc "Toplevel1" 1
    $top.tNo55 add $top.tNo55.t0 \
        -padding 0 -sticky nsew -state normal -text {Page 1} -image {} \
        -compound left -underline -1 
    set site_4_0  $top.tNo55.t0
    frame $top.tNo55.t1 \
        -background {#d9d9d9} -highlightcolor black 
    vTcl:DefineAlias "$top.tNo55.t1" "TNotebook1_t2" vTcl:WidgetProc "Toplevel1" 1
    $top.tNo55 add $top.tNo55.t1 \
        -padding 0 -sticky nsew -state normal -text {Page 2} -image {} \
        -compound left -underline -1 
    set site_4_1  $top.tNo55.t1
    frame $top.fra56 \
        -borderwidth 2 -relief groove -background {#d9d9d9} -height 576 \
        -highlightcolor black -width 272 
    vTcl:DefineAlias "$top.fra56" "Frame1" vTcl:WidgetProc "Toplevel1" 1
    set site_3_0 $top.fra56
    label $site_3_0.lab48 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -font TkDefaultFont -foreground {#000000} \
        -highlightcolor black -text Controls 
    vTcl:DefineAlias "$site_3_0.lab48" "Label1" vTcl:WidgetProc "Toplevel1" 1
    labelframe $site_3_0.lab43 \
        -font TkDefaultFont -foreground black -text A-Scan \
        -background {#d9d9d9} -height 105 -highlightcolor black -width 240 
    vTcl:DefineAlias "$site_3_0.lab43" "Labelframe1" vTcl:WidgetProc "Toplevel1" 1
    set site_4_0 $site_3_0.lab43
    button $site_4_0.but53 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -font TkDefaultFont -foreground {#000000} \
        -highlightcolor black -text Start 
    vTcl:DefineAlias "$site_4_0.but53" "Button1" vTcl:WidgetProc "Toplevel1" 1
    checkbutton $site_4_0.che54 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -font TkDefaultFont -foreground {#000000} \
        -highlightcolor black -justify left -text Save -variable che54 
    vTcl:DefineAlias "$site_4_0.che54" "Checkbutton1" vTcl:WidgetProc "Toplevel1" 1
    entry $site_4_0.ent57 \
        -background white -font TkFixedFont -foreground {#000000} \
        -highlightcolor black -insertbackground black \
        -selectbackground {#c4c4c4} -selectforeground black 
    vTcl:DefineAlias "$site_4_0.ent57" "Entry1" vTcl:WidgetProc "Toplevel1" 1
    message $site_4_0.mes45 \
        -background {#d9d9d9} -font TkDefaultFont -foreground {#000000} \
        -highlightcolor black -text Message -width 62 
    vTcl:DefineAlias "$site_4_0.mes45" "Message2_5" vTcl:WidgetProc "Toplevel1" 1
    place $site_4_0.but53 \
        -in $site_4_0 -x 9 -y 25 -width 71 -height 31 -anchor nw \
        -bordermode ignore 
    place $site_4_0.che54 \
        -in $site_4_0 -x 162 -y 29 -width 67 -height 23 -anchor nw \
        -bordermode ignore 
    place $site_4_0.ent57 \
        -in $site_4_0 -x 153 -y 70 -width 76 -relwidth 0 -height 23 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_0.mes45 \
        -in $site_4_0 -x 83 -y 70 -width 62 -height 25 -anchor nw \
        -bordermode ignore 
    labelframe $site_3_0.lab44 \
        -font TkDefaultFont -foreground black -text B-Scan \
        -background {#d9d9d9} -height 105 -highlightcolor black -width 240 
    vTcl:DefineAlias "$site_3_0.lab44" "Labelframe1_1" vTcl:WidgetProc "Toplevel1" 1
    set site_4_0 $site_3_0.lab44
    button $site_4_0.but61 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -font TkDefaultFont -foreground {#000000} \
        -highlightcolor black -text Start 
    vTcl:DefineAlias "$site_4_0.but61" "Button4" vTcl:WidgetProc "Toplevel1" 1
    message $site_4_0.mes74 \
        -background {#d9d9d9} -font TkDefaultFont -foreground {#000000} \
        -highlightcolor black -text Distance -width 62 
    vTcl:DefineAlias "$site_4_0.mes74" "Message2" vTcl:WidgetProc "Toplevel1" 1
    entry $site_4_0.ent75 \
        -background white -font TkFixedFont -foreground {#000000} \
        -highlightcolor black -insertbackground black \
        -selectbackground {#c4c4c4} -selectforeground black 
    vTcl:DefineAlias "$site_4_0.ent75" "Entry1_3" vTcl:WidgetProc "Toplevel1" 1
    message $site_4_0.mes76 \
        -background {#d9d9d9} -font TkDefaultFont -foreground {#000000} \
        -highlightcolor black -text Step -width 62 
    vTcl:DefineAlias "$site_4_0.mes76" "Message2_4" vTcl:WidgetProc "Toplevel1" 1
    entry $site_4_0.ent77 \
        -background white -font TkFixedFont -foreground {#000000} \
        -highlightcolor black -insertbackground black \
        -selectbackground {#c4c4c4} -selectforeground black 
    vTcl:DefineAlias "$site_4_0.ent77" "Entry1_4" vTcl:WidgetProc "Toplevel1" 1
    checkbutton $site_4_0.che94 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -font TkDefaultFont -foreground {#000000} \
        -highlightcolor black -justify left -text Save -variable che54 
    vTcl:DefineAlias "$site_4_0.che94" "Checkbutton1_15" vTcl:WidgetProc "Toplevel1" 1
    place $site_4_0.but61 \
        -in $site_4_0 -x 10 -y 20 -width 71 -height 31 -anchor nw \
        -bordermode ignore 
    place $site_4_0.mes74 \
        -in $site_4_0 -x 87 -y 25 -width 62 -relwidth 0 -height 25 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_0.ent75 \
        -in $site_4_0 -x 154 -y 27 -width 76 -height 23 -anchor nw \
        -bordermode ignore 
    place $site_4_0.mes76 \
        -in $site_4_0 -x 88 -y 63 -width 62 -height 25 -anchor nw \
        -bordermode ignore 
    place $site_4_0.ent77 \
        -in $site_4_0 -x 154 -y 67 -width 76 -height 23 -anchor nw \
        -bordermode ignore 
    place $site_4_0.che94 \
        -in $site_4_0 -x 10 -y 64 -width 67 -height 23 -anchor nw \
        -bordermode ignore 
    labelframe $site_3_0.lab45 \
        -font TkDefaultFont -foreground black -text C-Scan \
        -background {#d9d9d9} -height 165 -highlightcolor black -width 240 
    vTcl:DefineAlias "$site_3_0.lab45" "Labelframe1_2" vTcl:WidgetProc "Toplevel1" 1
    set site_4_0 $site_3_0.lab45
    button $site_4_0.but78 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -font TkDefaultFont -foreground {#000000} \
        -highlightcolor black -text Start 
    vTcl:DefineAlias "$site_4_0.but78" "Button4_5" vTcl:WidgetProc "Toplevel1" 1
    message $site_4_0.mes79 \
        -background {#d9d9d9} -font TkDefaultFont -foreground {#000000} \
        -highlightcolor black -text {x Dist} -width 62 
    vTcl:DefineAlias "$site_4_0.mes79" "Message2_6" vTcl:WidgetProc "Toplevel1" 1
    entry $site_4_0.ent80 \
        -background white -font TkFixedFont -foreground {#000000} \
        -highlightcolor black -insertbackground black \
        -selectbackground {#c4c4c4} -selectforeground black 
    vTcl:DefineAlias "$site_4_0.ent80" "Entry1_5" vTcl:WidgetProc "Toplevel1" 1
    entry $site_4_0.ent81 \
        -background white -font TkFixedFont -foreground {#000000} \
        -highlightcolor black -insertbackground black \
        -selectbackground {#c4c4c4} -selectforeground black 
    vTcl:DefineAlias "$site_4_0.ent81" "Entry1_1" vTcl:WidgetProc "Toplevel1" 1
    entry $site_4_0.ent82 \
        -background white -font TkFixedFont -foreground {#000000} \
        -highlightcolor black -insertbackground black \
        -selectbackground {#c4c4c4} -selectforeground black 
    vTcl:DefineAlias "$site_4_0.ent82" "Entry1_6" vTcl:WidgetProc "Toplevel1" 1
    entry $site_4_0.ent83 \
        -background white -font TkFixedFont -foreground {#000000} \
        -highlightcolor black -insertbackground black \
        -selectbackground {#c4c4c4} -selectforeground black 
    vTcl:DefineAlias "$site_4_0.ent83" "Entry1_2" vTcl:WidgetProc "Toplevel1" 1
    entry $site_4_0.ent84 \
        -background white -font TkFixedFont -foreground {#000000} \
        -highlightcolor black -insertbackground black \
        -selectbackground {#c4c4c4} -selectforeground black 
    vTcl:DefineAlias "$site_4_0.ent84" "Entry1_7" vTcl:WidgetProc "Toplevel1" 1
    entry $site_4_0.ent85 \
        -background white -font TkFixedFont -foreground {#000000} \
        -highlightcolor black -insertbackground black \
        -selectbackground {#c4c4c4} -selectforeground black 
    vTcl:DefineAlias "$site_4_0.ent85" "Entry1_8" vTcl:WidgetProc "Toplevel1" 1
    message $site_4_0.mes86 \
        -background {#d9d9d9} -font TkDefaultFont -foreground {#000000} \
        -highlightcolor black -text {y Dist} -width 62 
    vTcl:DefineAlias "$site_4_0.mes86" "Message2_7" vTcl:WidgetProc "Toplevel1" 1
    message $site_4_0.mes87 \
        -background {#d9d9d9} -font TkDefaultFont -foreground {#000000} \
        -highlightcolor black -text {z Dist} -width 62 
    vTcl:DefineAlias "$site_4_0.mes87" "Message2_8" vTcl:WidgetProc "Toplevel1" 1
    message $site_4_0.mes88 \
        -background {#d9d9d9} -font TkDefaultFont -foreground {#000000} \
        -highlightcolor black -text {x Step} -width 62 
    vTcl:DefineAlias "$site_4_0.mes88" "Message2_3" vTcl:WidgetProc "Toplevel1" 1
    message $site_4_0.mes90 \
        -background {#d9d9d9} -font TkDefaultFont -foreground {#000000} \
        -highlightcolor black -text {y Step} -width 62 
    vTcl:DefineAlias "$site_4_0.mes90" "Message2_9" vTcl:WidgetProc "Toplevel1" 1
    message $site_4_0.mes91 \
        -background {#d9d9d9} -font TkDefaultFont -foreground {#000000} \
        -highlightcolor black -text {z Step} -width 62 
    vTcl:DefineAlias "$site_4_0.mes91" "Message2_6" vTcl:WidgetProc "Toplevel1" 1
    checkbutton $site_4_0.che92 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -font TkDefaultFont -foreground {#000000} \
        -highlightcolor black -justify left -text Save -variable che54 
    vTcl:DefineAlias "$site_4_0.che92" "Checkbutton1_10" vTcl:WidgetProc "Toplevel1" 1
    place $site_4_0.but78 \
        -in $site_4_0 -x 9 -y 23 -width 71 -height 31 -anchor nw \
        -bordermode ignore 
    place $site_4_0.mes79 \
        -in $site_4_0 -x 10 -y 60 -width 62 -relwidth 0 -height 25 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_0.ent80 \
        -in $site_4_0 -x 10 -y 86 -width 66 -relwidth 0 -height 23 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_0.ent81 \
        -in $site_4_0 -x 10 -y 130 -width 66 -relwidth 0 -height 23 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_0.ent82 \
        -in $site_4_0 -x 87 -y 86 -width 66 -relwidth 0 -height 23 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_0.ent83 \
        -in $site_4_0 -x 86 -y 130 -width 66 -relwidth 0 -height 23 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_0.ent84 \
        -in $site_4_0 -x 160 -y 86 -width 66 -height 23 -anchor nw \
        -bordermode ignore 
    place $site_4_0.ent85 \
        -in $site_4_0 -x 161 -y 130 -width 66 -height 23 -anchor nw \
        -bordermode ignore 
    place $site_4_0.mes86 \
        -in $site_4_0 -x 90 -y 60 -width 62 -height 25 -anchor nw \
        -bordermode ignore 
    place $site_4_0.mes87 \
        -in $site_4_0 -x 160 -y 60 -width 62 -height 25 -anchor nw \
        -bordermode ignore 
    place $site_4_0.mes88 \
        -in $site_4_0 -x 13 -y 113 -width 62 -relwidth 0 -height 15 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_0.mes90 \
        -in $site_4_0 -x 91 -y 111 -width 62 -height 15 -anchor nw \
        -bordermode ignore 
    place $site_4_0.mes91 \
        -in $site_4_0 -x 164 -y 112 -width 62 -height 15 -anchor nw \
        -bordermode ignore 
    place $site_4_0.che92 \
        -in $site_4_0 -x 160 -y 25 -width 67 -height 23 -anchor nw \
        -bordermode ignore 
    label $site_3_0.lab46 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -font TkDefaultFont -foreground {#000000} \
        -highlightcolor black -text {Motor Controller : Not Connected} 
    vTcl:DefineAlias "$site_3_0.lab46" "Label2" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab47 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -font TkDefaultFont -foreground {#000000} \
        -highlightcolor black -text {Oscilloscope : Not Connected} 
    vTcl:DefineAlias "$site_3_0.lab47" "Label3" vTcl:WidgetProc "Toplevel1" 1
    label $site_3_0.lab49 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -font TkDefaultFont -foreground {#000000} \
        -highlightcolor black -text {Waveform Generator : Not Connected} 
    vTcl:DefineAlias "$site_3_0.lab49" "Label4" vTcl:WidgetProc "Toplevel1" 1
    checkbutton $site_3_0.che58 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -font TkDefaultFont -foreground {#000000} \
        -highlightcolor black -justify left -text Envelope -variable che58 
    vTcl:DefineAlias "$site_3_0.che58" "Checkbutton2" vTcl:WidgetProc "Toplevel1" 1
    checkbutton $site_3_0.che59 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -font TkDefaultFont -foreground {#000000} \
        -highlightcolor black -justify left -text {Do XCorr} -variable che59 
    vTcl:DefineAlias "$site_3_0.che59" "Checkbutton3" vTcl:WidgetProc "Toplevel1" 1
    place $site_3_0.lab48 \
        -in $site_3_0 -x 10 -y 10 -width 69 -relwidth 0 -height 21 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.lab43 \
        -in $site_3_0 -x 10 -y 50 -width 240 -relwidth 0 -height 105 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.lab44 \
        -in $site_3_0 -x 10 -y 170 -width 240 -relwidth 0 -height 105 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.lab45 \
        -in $site_3_0 -x 10 -y 290 -width 240 -relwidth 0 -height 165 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.lab46 \
        -in $site_3_0 -x 8 -y 478 -width 249 -relwidth 0 -height 21 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.lab47 \
        -in $site_3_0 -x 10 -y 508 -width 239 -relwidth 0 -height 21 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.lab49 \
        -in $site_3_0 -x 5 -y 536 -width 249 -relwidth 0 -height 21 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.che58 \
        -in $site_3_0 -x 163 -y 4 -width 87 -relwidth 0 -height 23 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.che59 \
        -in $site_3_0 -x 162 -y 29 -width 87 -relwidth 0 -height 23 \
        -relheight 0 -anchor nw -bordermode ignore 
    ###################
    # SETTING GEOMETRY
    ###################
    place $top.can43 \
        -in $top -x 300 -y 20 -width 981 -relwidth 0 -height 561 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.but60 \
        -in $top -x 7 -y 632 -width 111 -relwidth 0 -height 31 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.lab65 \
        -in $top -x 797 -y 590 -width 490 -relwidth 0 -height 55 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.lab93 \
        -in $top -x 307 -y 591 -width 480 -relwidth 0 -height 55 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.tPr43 \
        -in $top -x 150 -y 634 -width 100 -height 19 -anchor nw \
        -bordermode ignore 
    place $top.tNo55 \
        -in $top -x 0 -y 0 -width 292 -relwidth 0 -height 616 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.fra56 \
        -in $top -x 10 -y 30 -width 272 -relwidth 0 -height 576 -relheight 0 \
        -anchor nw -bordermode ignore 

    vTcl:FireEvent $base <<Ready>>
}

#############################################################################
## Binding tag:  _TopLevel

bind "_TopLevel" <<Create>> {
    if {![info exists _topcount]} {set _topcount 0}; incr _topcount
}
bind "_TopLevel" <<DeleteWindow>> {
    if {[set ::%W::_modal]} {
                vTcl:Toplevel:WidgetProc %W endmodal
            } else {
                destroy %W; if {$_topcount == 0} {exit}
            }
}
bind "_TopLevel" <Destroy> {
    if {[winfo toplevel %W] == "%W"} {incr _topcount -1}
}
#############################################################################
## Binding tag:  _vTclBalloon


if {![info exists vTcl(sourcing)]} {
bind "_vTclBalloon" <<KillBalloon>> {
    namespace eval ::vTcl::balloon {
        after cancel $id
        if {[winfo exists .vTcl.balloon]} {
            destroy .vTcl.balloon
        }
        set set 0
    }
}
bind "_vTclBalloon" <<vTclBalloon>> {
    if {$::vTcl::balloon::first != 1} {break}
    namespace eval ::vTcl::balloon {
        set first 2
        if {![winfo exists .vTcl]} {
            toplevel .vTcl; wm withdraw .vTcl
        }
        if {![winfo exists .vTcl.balloon]} {
            toplevel .vTcl.balloon -bg black
        }
        wm overrideredirect .vTcl.balloon 1
        label .vTcl.balloon.l  -text ${%W} -relief flat  -bg #ffffaa -fg black -padx 2 -pady 0 -anchor w
        pack .vTcl.balloon.l -side left -padx 1 -pady 1
        wm geometry  .vTcl.balloon  +[expr {[winfo rootx %W]+[winfo width %W]/2}]+[expr {[winfo rooty %W]+[winfo height %W]+4}]
        set set 1
    }
}
bind "_vTclBalloon" <Button> {
    namespace eval ::vTcl::balloon {
        set first 0
    }
    vTcl:FireEvent %W <<KillBalloon>>
}
bind "_vTclBalloon" <Enter> {
    namespace eval ::vTcl::balloon {
        ## self defining balloon?
        if {![info exists %W]} {
            vTcl:FireEvent %W <<SetBalloon>>
        }
        set set 0
        set first 1
        set id [after 500 {vTcl:FireEvent %W <<vTclBalloon>>}]
    }
}
bind "_vTclBalloon" <Leave> {
    namespace eval ::vTcl::balloon {
        set first 0
    }
    vTcl:FireEvent %W <<KillBalloon>>
}
bind "_vTclBalloon" <Motion> {
    namespace eval ::vTcl::balloon {
        if {!$set} {
            after cancel $id
            set id [after 500 {vTcl:FireEvent %W <<vTclBalloon>>}]
        }
    }
}
}

set btop ""
if {$vTcl(borrow)} {
    set btop .bor[expr int([expr rand() * 100])]
    while {[lsearch $btop $vTcl(tops)] != -1} {
        set btop .bor[expr int([expr rand() * 100])]
    }
}
set vTcl(btop) $btop
Window show .
Window show .top42 $btop
if {$vTcl(borrow)} {
    $btop configure -background plum
}

