#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 4.19
#  in conjunction with Tcl version 8.6
#    Jan 01, 2019 05:25:46 PM EET  platform: Linux

import sys

try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

import unknown2_support

def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = tk.Tk()
    unknown2_support.set_Tk_var()
    top = Toplevel1 (root)
    unknown2_support.init(root, top)
    root.mainloop()

w = None
def create_Toplevel1(root, *args, **kwargs):
    '''Starting point when module is imported by another program.'''
    global w, w_win, rt
    rt = root
    w = tk.Toplevel (root)
    unknown2_support.set_Tk_var()
    top = Toplevel1 (w)
    unknown2_support.init(w, top, *args, **kwargs)
    return (w, top)

def destroy_Toplevel1():
    global w
    w.destroy()
    w = None

class Toplevel1:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85' 
        _ana2color = '#ececec' # Closest X11 color: 'gray92' 
        self.style = ttk.Style()
        if sys.platform == "win32":
            self.style.theme_use('winnative')
        self.style.configure('.',background=_bgcolor)
        self.style.configure('.',foreground=_fgcolor)
        self.style.configure('.',font="TkDefaultFont")
        self.style.map('.',background=
            [('selected', _compcolor), ('active',_ana2color)])

        top.geometry("1299x713+67+27")
        top.title("New Toplevel")
        top.configure(background="#707070")
        top.configure(highlightcolor="black")

        self.Canvas1 = tk.Canvas(top)
        self.Canvas1.place(relx=0.231, rely=0.028, relheight=0.871
                , relwidth=0.755)
        self.Canvas1.configure(borderwidth="2")
        self.Canvas1.configure(relief='ridge')
        self.Canvas1.configure(selectbackground="#c4c4c4")
        self.Canvas1.configure(width=981)

        self.Button3 = tk.Button(top)
        self.Button3.place(relx=0.0, rely=0.94, height=31, width=111)
        self.Button3.configure(activebackground="#f9f9f9")
        self.Button3.configure(text='''Reconnect''')

        self.Labelframe2 = tk.LabelFrame(top)
        self.Labelframe2.place(relx=0.608, rely=0.905, relheight=0.077
                , relwidth=0.377)
        self.Labelframe2.configure(relief='groove')
        self.Labelframe2.configure(text='''Save as''')
        self.Labelframe2.configure(width=490)

        self.Message1 = tk.Message(self.Labelframe2)
        self.Message1.place(relx=0.204, rely=0.273, relheight=0.455
                , relwidth=0.453, bordermode='ignore')
        self.Message1.configure(text='''Message''')
        self.Message1.configure(width=222)

        self.Button2 = tk.Button(self.Labelframe2)
        self.Button2.place(relx=0.01, rely=0.273, height=31, width=71
                , bordermode='ignore')
        self.Button2.configure(activebackground="#f9f9f9")
        self.Button2.configure(text='''Browse''')

        self.Entry2 = tk.Entry(self.Labelframe2)
        self.Entry2.place(relx=0.673, rely=0.364, height=23, relwidth=0.298
                , bordermode='ignore')
        self.Entry2.configure(background="white")
        self.Entry2.configure(font="TkFixedFont")
        self.Entry2.configure(selectbackground="#c4c4c4")

        self.Labelframe2_11 = tk.LabelFrame(top)
        self.Labelframe2_11.place(relx=0.231, rely=0.912, relheight=0.077
                , relwidth=0.37)
        self.Labelframe2_11.configure(relief='groove')
        self.Labelframe2_11.configure(text='''Transmit Signal''')
        self.Labelframe2_11.configure(width=480)

        self.Message1_12 = tk.Message(self.Labelframe2_11)
        self.Message1_12.place(relx=0.208, rely=0.364, relheight=0.455
                , relwidth=0.463, bordermode='ignore')
        self.Message1_12.configure(text='''Message''')
        self.Message1_12.configure(width=222)

        self.Button2_13 = tk.Button(self.Labelframe2_11)
        self.Button2_13.place(relx=0.01, rely=0.273, height=31, width=71
                , bordermode='ignore')
        self.Button2_13.configure(activebackground="#f9f9f9")
        self.Button2_13.configure(text='''Browse''')

        self.Entry2_14 = tk.Entry(self.Labelframe2_11)
        self.Entry2_14.place(relx=0.677, rely=0.364, height=23, relwidth=0.304
                , bordermode='ignore')
        self.Entry2_14.configure(background="white")
        self.Entry2_14.configure(font="TkFixedFont")
        self.Entry2_14.configure(selectbackground="#c4c4c4")

        self.TProgressbar1 = ttk.Progressbar(top)
        self.TProgressbar1.place(relx=0.112, rely=0.947, relwidth=0.077
                , relheight=0.0, height=19)

        self.style.configure('TNotebook.Tab', background=_bgcolor)
        self.style.configure('TNotebook.Tab', foreground=_fgcolor)
        self.style.map('TNotebook.Tab', background=
            [('selected', _compcolor), ('active',_ana2color)])
        self.TNotebook1 = ttk.Notebook(top)
        self.TNotebook1.place(relx=0.0, rely=0.028, relheight=0.878
                , relwidth=0.225)
        self.TNotebook1.configure(width=292)
        self.TNotebook1.configure(takefocus="")
        self.TNotebook1_t0 = tk.Frame(self.TNotebook1)
        self.TNotebook1.add(self.TNotebook1_t0, padding=3)
        self.TNotebook1.tab(0, text="Controls",compound="left",underline="-1",)
        self.TNotebook1_t1 = tk.Frame(self.TNotebook1)
        self.TNotebook1.add(self.TNotebook1_t1, padding=3)
        self.TNotebook1.tab(1, text="Plot Tools", compound="left", underline="-1"
                ,)
        self.TNotebook1_t2 = tk.Frame(self.TNotebook1)
        self.TNotebook1.add(self.TNotebook1_t2, padding=3)
        self.TNotebook1.tab(2, text="Signal Generation", compound="none"
                ,underline="-1", )

        self.Frame1 = tk.Frame(self.TNotebook1_t0)
        self.Frame1.place(relx=0.017, rely=0.017, relheight=0.96, relwidth=0.938)

        self.Frame1.configure(relief='groove')
        self.Frame1.configure(borderwidth="2")
        self.Frame1.configure(relief='groove')
        self.Frame1.configure(width=272)

        self.Label1 = tk.Label(self.Frame1)
        self.Label1.place(relx=0.037, rely=0.017, height=21, width=69)
        self.Label1.configure(activebackground="#f9f9f9")
        self.Label1.configure(text='''Controls''')

        self.Labelframe1 = tk.LabelFrame(self.Frame1)
        self.Labelframe1.place(relx=0.037, rely=0.087, relheight=0.182
                , relwidth=0.882)
        self.Labelframe1.configure(relief='groove')
        self.Labelframe1.configure(text='''A-Scan''')
        self.Labelframe1.configure(width=240)

        self.Button1 = tk.Button(self.Labelframe1)
        self.Button1.place(relx=0.021, rely=0.238, height=31, width=71
                , bordermode='ignore')
        self.Button1.configure(activebackground="#f9f9f9")
        self.Button1.configure(text='''Start''')

        self.Checkbutton1 = tk.Checkbutton(self.Labelframe1)
        self.Checkbutton1.place(relx=0.667, rely=0.238, relheight=0.219
                , relwidth=0.279, bordermode='ignore')
        self.Checkbutton1.configure(activebackground="#f9f9f9")
        self.Checkbutton1.configure(justify='left')
        self.Checkbutton1.configure(text='''Save''')
        self.Checkbutton1.configure(variable=unknown2_support.che54)

        self.Entry1 = tk.Entry(self.Labelframe1)
        self.Entry1.place(relx=0.625, rely=0.667, height=23, relwidth=0.317
                , bordermode='ignore')
        self.Entry1.configure(background="white")
        self.Entry1.configure(font="TkFixedFont")
        self.Entry1.configure(selectbackground="#c4c4c4")

        self.Message2_5 = tk.Message(self.Labelframe1)
        self.Message2_5.place(relx=0.333, rely=0.667, relheight=0.238
                , relwidth=0.258, bordermode='ignore')
        self.Message2_5.configure(text='''Message''')
        self.Message2_5.configure(width=62)

        self.Labelframe1_1 = tk.LabelFrame(self.Frame1)
        self.Labelframe1_1.place(relx=0.037, rely=0.295, relheight=0.182
                , relwidth=0.882)
        self.Labelframe1_1.configure(relief='groove')
        self.Labelframe1_1.configure(text='''B-Scan''')
        self.Labelframe1_1.configure(width=240)

        self.Button4 = tk.Button(self.Labelframe1_1)
        self.Button4.place(relx=0.042, rely=0.19, height=31, width=71
                , bordermode='ignore')
        self.Button4.configure(activebackground="#f9f9f9")
        self.Button4.configure(text='''Start''')

        self.Message2 = tk.Message(self.Labelframe1_1)
        self.Message2.place(relx=0.354, rely=0.238, relheight=0.238
                , relwidth=0.258, bordermode='ignore')
        self.Message2.configure(text='''Distance''')
        self.Message2.configure(width=62)

        self.Entry1_3 = tk.Entry(self.Labelframe1_1)
        self.Entry1_3.place(relx=0.625, rely=0.238, height=23, relwidth=0.317
                , bordermode='ignore')
        self.Entry1_3.configure(background="white")
        self.Entry1_3.configure(font="TkFixedFont")
        self.Entry1_3.configure(selectbackground="#c4c4c4")

        self.Message2_4 = tk.Message(self.Labelframe1_1)
        self.Message2_4.place(relx=0.354, rely=0.571, relheight=0.238
                , relwidth=0.258, bordermode='ignore')
        self.Message2_4.configure(text='''Step''')
        self.Message2_4.configure(width=62)

        self.Entry1_4 = tk.Entry(self.Labelframe1_1)
        self.Entry1_4.place(relx=0.625, rely=0.619, height=23, relwidth=0.317
                , bordermode='ignore')
        self.Entry1_4.configure(background="white")
        self.Entry1_4.configure(font="TkFixedFont")
        self.Entry1_4.configure(selectbackground="#c4c4c4")

        self.Checkbutton1_15 = tk.Checkbutton(self.Labelframe1_1)
        self.Checkbutton1_15.place(relx=0.042, rely=0.571, relheight=0.219
                , relwidth=0.279, bordermode='ignore')
        self.Checkbutton1_15.configure(activebackground="#f9f9f9")
        self.Checkbutton1_15.configure(justify='left')
        self.Checkbutton1_15.configure(text='''Save''')
        self.Checkbutton1_15.configure(variable=unknown2_support.che54)

        self.Labelframe1_2 = tk.LabelFrame(self.Frame1)
        self.Labelframe1_2.place(relx=0.037, rely=0.503, relheight=0.286
                , relwidth=0.882)
        self.Labelframe1_2.configure(relief='groove')
        self.Labelframe1_2.configure(text='''C-Scan''')
        self.Labelframe1_2.configure(width=240)

        self.Button4_5 = tk.Button(self.Labelframe1_2)
        self.Button4_5.place(relx=0.021, rely=0.121, height=31, width=71
                , bordermode='ignore')
        self.Button4_5.configure(activebackground="#f9f9f9")
        self.Button4_5.configure(text='''Start''')

        self.Message2_7 = tk.Message(self.Labelframe1_2)
        self.Message2_7.place(relx=0.042, rely=0.364, relheight=0.152
                , relwidth=0.258, bordermode='ignore')
        self.Message2_7.configure(text='''x Dist''')
        self.Message2_7.configure(width=62)

        self.Entry1_5 = tk.Entry(self.Labelframe1_2)
        self.Entry1_5.place(relx=0.042, rely=0.515, height=23, relwidth=0.275
                , bordermode='ignore')
        self.Entry1_5.configure(background="white")
        self.Entry1_5.configure(font="TkFixedFont")
        self.Entry1_5.configure(selectbackground="#c4c4c4")

        self.Entry1_1 = tk.Entry(self.Labelframe1_2)
        self.Entry1_1.place(relx=0.042, rely=0.788, height=23, relwidth=0.275
                , bordermode='ignore')
        self.Entry1_1.configure(background="white")
        self.Entry1_1.configure(font="TkFixedFont")
        self.Entry1_1.configure(selectbackground="#c4c4c4")

        self.Entry1_6 = tk.Entry(self.Labelframe1_2)
        self.Entry1_6.place(relx=0.354, rely=0.515, height=23, relwidth=0.275
                , bordermode='ignore')
        self.Entry1_6.configure(background="white")
        self.Entry1_6.configure(font="TkFixedFont")
        self.Entry1_6.configure(selectbackground="#c4c4c4")

        self.Entry1_2 = tk.Entry(self.Labelframe1_2)
        self.Entry1_2.place(relx=0.354, rely=0.788, height=23, relwidth=0.275
                , bordermode='ignore')
        self.Entry1_2.configure(background="white")
        self.Entry1_2.configure(font="TkFixedFont")
        self.Entry1_2.configure(selectbackground="#c4c4c4")

        self.Entry1_7 = tk.Entry(self.Labelframe1_2)
        self.Entry1_7.place(relx=0.667, rely=0.515, height=23, relwidth=0.275
                , bordermode='ignore')
        self.Entry1_7.configure(background="white")
        self.Entry1_7.configure(font="TkFixedFont")
        self.Entry1_7.configure(selectbackground="#c4c4c4")

        self.Entry1_8 = tk.Entry(self.Labelframe1_2)
        self.Entry1_8.place(relx=0.667, rely=0.788, height=23, relwidth=0.275
                , bordermode='ignore')
        self.Entry1_8.configure(background="white")
        self.Entry1_8.configure(font="TkFixedFont")
        self.Entry1_8.configure(selectbackground="#c4c4c4")

        self.Message2_8 = tk.Message(self.Labelframe1_2)
        self.Message2_8.place(relx=0.354, rely=0.364, relheight=0.152
                , relwidth=0.258, bordermode='ignore')
        self.Message2_8.configure(text='''y Dist''')
        self.Message2_8.configure(width=62)

        self.Message2_9 = tk.Message(self.Labelframe1_2)
        self.Message2_9.place(relx=0.667, rely=0.364, relheight=0.152
                , relwidth=0.258, bordermode='ignore')
        self.Message2_9.configure(text='''z Dist''')
        self.Message2_9.configure(width=62)

        self.Message2_3 = tk.Message(self.Labelframe1_2)
        self.Message2_3.place(relx=0.042, rely=0.667, relheight=0.091
                , relwidth=0.258, bordermode='ignore')
        self.Message2_3.configure(text='''x Step''')
        self.Message2_3.configure(width=62)

        self.Message2_10 = tk.Message(self.Labelframe1_2)
        self.Message2_10.place(relx=0.354, rely=0.667, relheight=0.091
                , relwidth=0.258, bordermode='ignore')
        self.Message2_10.configure(text='''y Step''')
        self.Message2_10.configure(width=62)

        self.Message2_6 = tk.Message(self.Labelframe1_2)
        self.Message2_6.place(relx=0.667, rely=0.667, relheight=0.091
                , relwidth=0.258, bordermode='ignore')
        self.Message2_6.configure(text='''z Step''')
        self.Message2_6.configure(width=62)

        self.Checkbutton1_10 = tk.Checkbutton(self.Labelframe1_2)
        self.Checkbutton1_10.place(relx=0.667, rely=0.152, relheight=0.139
                , relwidth=0.279, bordermode='ignore')
        self.Checkbutton1_10.configure(activebackground="#f9f9f9")
        self.Checkbutton1_10.configure(justify='left')
        self.Checkbutton1_10.configure(text='''Save''')
        self.Checkbutton1_10.configure(variable=unknown2_support.che54)

        self.Label2 = tk.Label(self.Frame1)
        self.Label2.place(relx=0.018, rely=0.825, height=21, width=249)
        self.Label2.configure(activebackground="#f9f9f9")
        self.Label2.configure(text='''Motor Controller : Not Connected''')

        self.Label3 = tk.Label(self.Frame1)
        self.Label3.place(relx=0.037, rely=0.877, height=21, width=239)
        self.Label3.configure(activebackground="#f9f9f9")
        self.Label3.configure(text='''Oscilloscope : Not Connected''')

        self.Label4 = tk.Label(self.Frame1)
        self.Label4.place(relx=0.018, rely=0.929, height=21, width=249)
        self.Label4.configure(activebackground="#f9f9f9")
        self.Label4.configure(text='''Waveform Generator : Not Connected''')

        self.Checkbutton2 = tk.Checkbutton(self.Frame1)
        self.Checkbutton2.place(relx=0.588, rely=0.0, relheight=0.04
                , relwidth=0.32)
        self.Checkbutton2.configure(activebackground="#f9f9f9")
        self.Checkbutton2.configure(justify='left')
        self.Checkbutton2.configure(text='''Envelope''')
        self.Checkbutton2.configure(variable=unknown2_support.che58)

        self.Checkbutton3 = tk.Checkbutton(self.Frame1)
        self.Checkbutton3.place(relx=0.588, rely=0.043, relheight=0.04
                , relwidth=0.32)
        self.Checkbutton3.configure(activebackground="#f9f9f9")
        self.Checkbutton3.configure(justify='left')
        self.Checkbutton3.configure(text='''Do XCorr''')
        self.Checkbutton3.configure(variable=unknown2_support.che59)

if __name__ == '__main__':
    vp_start_gui()





